'use strict'
var Koop = require('koop')
var config = require('config')
var koop = Koop(config)
var yelp = require('koop-yelp')
koop.register(yelp)
var express = require('express')
var app = express()
app.use(koop)
app.listen(8080, function () { console.log('were up and running') })
